import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google"
import { Toaster } from "@/components/ui/toaster";
import { auth } from "@/auth";
import NavBar from "@/components/Global/NavBar";
import { Toaster as Sonner } from "@/components/ui/sonner"
import { Providers } from "./providers";
import prisma from "@/lib/db";
import QueryProvider from "@/providers/QueryClientProvider";


const font = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "LegalHub",
  description: "Generated by LegalHub",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  const preferences = session?.user ? await prisma.preferences.findUnique({
    where: { userId: session.user.id }
  }) : null
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${font.className} antialiased`}
      >
        <NavBar />
        <QueryProvider>
          <Providers session={session} preferences={preferences}>
            {children}
          </Providers>
        </QueryProvider>
        <Toaster />
        <Sonner />
      </body>
    </html>
  );
}
